// Map slugs to folder names
const folderMap: Record<string, string> = {
  "datalines-with-grid": "DatalinesWithGrid",
  "ascii-rain": "AsciiRain",
  "border-beam-corner-cut-card": "BorderBeamCornerCutCard",
  "accent-frame": "AccentFrame",
  "glitch-text": "GlitchText",
  "corner-cut-button": "CornerCutButton",
  "neon-glow-corner-cut-card": "NeonGlowCornerCutCard",
  badge: "Badge",
  navbar: "NavBar",
  footer: "Footer",
  timeline: "Timeline",
  "neon-glow": "NeonGlow",
  "glyph-city": "GlyphCity",
  "cyber-circuit": "CyberCircuit",
  "neon-input": "NeonInput",
  hexagons: "Hexagons",
  "card-slider": "CardSlider",
  "notch-card": "NotchCard",
  crosshair: "Crosshair",
  "outline-text": "OutlineText",
  pluviophile: "Pluviophile",
  "holographic-terrain": "HolographicTerrain",
  "neon-modal": "Modal",
  "neon-line-chart": "NeonLineChart",
  "neon-bar-chart": "NeonBarChart",
  "neon-donut-chart": "NeonDonutChart",
  "neon-sparkline": "NeonSparkline",
  "stat-card": "StatCard",
  "neon-table": "NeonTable",
  "progress-bar": "ProgressBar",
  "circular-progress": "CircularProgress",
  "arrow-loader": "ArrowLoader",
  "neon-toggle": "NeonToggle",
  "neon-checkbox": "NeonCheckbox",
  "neon-select": "NeonSelect",
};
export default folderMap;
